
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inspinia_MVC5_SeedProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mobiledata
{

    public int id { get; set; }

    public string title { get; set; }

    public string location { get; set; }

    public string price { get; set; }

    public string usr { get; set; }

    public string cell { get; set; }

    public string img1 { get; set; }

    public string img2 { get; set; }

    public string img3 { get; set; }

    public string description { get; set; }

    public string brand { get; set; }

}

}
